// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfVtkdJAZfMrcNtfwTPonrQKbIuTGdi2c',
    appId: '1:688238971596:web:2781f8e15ced6f64355069',
    messagingSenderId: '688238971596',
    projectId: 'auth-modul-e22de',
    authDomain: 'auth-modul-e22de.firebaseapp.com',
    storageBucket: 'auth-modul-e22de.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzQJpRo_Ur5jHxM2ej2h17OKJ-qaxNA2U',
    appId: '1:688238971596:android:271f46caf606a3db355069',
    messagingSenderId: '688238971596',
    projectId: 'auth-modul-e22de',
    storageBucket: 'auth-modul-e22de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3pwxkcMJXVDXe5Kcr22tZYitpaMwVyzM',
    appId: '1:688238971596:ios:24a7891116f56f01355069',
    messagingSenderId: '688238971596',
    projectId: 'auth-modul-e22de',
    storageBucket: 'auth-modul-e22de.firebasestorage.app',
    iosBundleId: 'com.example.coba456',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3pwxkcMJXVDXe5Kcr22tZYitpaMwVyzM',
    appId: '1:688238971596:ios:24a7891116f56f01355069',
    messagingSenderId: '688238971596',
    projectId: 'auth-modul-e22de',
    storageBucket: 'auth-modul-e22de.firebasestorage.app',
    iosBundleId: 'com.example.coba456',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfVtkdJAZfMrcNtfwTPonrQKbIuTGdi2c',
    appId: '1:688238971596:web:9684dd85db8b676f355069',
    messagingSenderId: '688238971596',
    projectId: 'auth-modul-e22de',
    authDomain: 'auth-modul-e22de.firebaseapp.com',
    storageBucket: 'auth-modul-e22de.firebasestorage.app',
  );
}
